-- ═══════════════════════════════════════════════════════════════
-- LCSW Exam Prep v2 — database schema (Postgres / Netlify DB / Neon)
--
-- Where to run it: Netlify dashboard → your site → Extensions →
-- Netlify DB → "Open in Neon" → SQL Editor → paste this → Run.
-- Safe to run more than once (everything is IF NOT EXISTS).
--
-- Note: the app's functions also create these tables automatically on
-- the first signup, so running this by hand is optional — but doing it
-- up front lets you confirm the database is wired before anyone signs up.
-- ═══════════════════════════════════════════════════════════════

-- User accounts. Passwords are stored ONLY as bcrypt hashes,
-- generated by the auth function — never plain text.
CREATE TABLE IF NOT EXISTS users (
  id            SERIAL       PRIMARY KEY,
  email         TEXT         UNIQUE NOT NULL,      -- lowercased by the app
  password_hash TEXT         NOT NULL,             -- bcrypt, cost 10
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One progress blob per user: the app's entire localStorage store as JSONB
-- (per-question spaced-repetition history, sessions, stars, notes, trap
-- counts, coach state, exam date). Upserted by the progress function.
CREATE TABLE IF NOT EXISTS progress (
  user_id    INTEGER      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  data       JSONB        NOT NULL,
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Verification (run after the script; both should return 0 rows, no errors) ──
-- SELECT * FROM users LIMIT 5;
-- SELECT user_id, updated_at, jsonb_typeof(data) FROM progress LIMIT 5;

-- ── Handy admin queries for later ──
-- Who has an account:
--   SELECT id, email, created_at FROM users ORDER BY created_at;
-- When each person last synced:
--   SELECT u.email, p.updated_at FROM users u JOIN progress p ON p.user_id = u.id ORDER BY p.updated_at DESC;
-- Delete one account entirely (progress cascades):
--   DELETE FROM users WHERE email = 'person@example.com';
